services:
  mysql:
    image: mysql:8.0
    container_name: careerflow_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: careerflow
    ports:
      - "3308:3306"
    volumes:
      - careerflow_mysql_data:/var/lib/mysql

volumes:
  careerflow_mysql_data: